<?php

namespace IronWeb\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findOneBySlug($slug)
	{
    $qb = $this->createQueryBuilder('n')
      ->where('n.slug = :slug')
      ->setParameter('slug', $slug);

    return $qb->getQuery()->getSingleResult();
	}
}

